FROM nvidia/cuda:9.1-devel-ubuntu16.04

RUN apt-get update
RUN apt-get install -y install git build-essential cmake libuv1-dev libmicrohttpd-dev
RUN git clone https://github.com/xmrig/xmrig-nvidia.git /opt/xmrig-nvidia
RUN mkdir /opt/xmrig-nvidia/build && cd /opt/xmrig-nvidia/build && cmake .. && make

WORKDIR /opt/xmrig-nvidia/build

ENTRYPOINT ["./xmrig-nvidia"]
